---
kind: pipeline
type: docker
name: default

clone:
  depth: 2

steps:
  - name: restore-cache-with-filesystem
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: 'filesystem'
      restore: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "go.mod" }}_{{ checksum "go.sum" }}_{{ arch }}_{{ os }}'
      archive_format: 'gzip'
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - 'node_modules'
    volumes:
      - name: cache
        path: /tmp/cache

  - name: install
    image: node:14
    pull: if-not-exists
    commands:
      - yarn

  - name: prebuild
    image: node:14
    commands:
      - yarn lint
      - yarn t

  - name: build
    image: node:14
    commands:
      - yarn build

  - name: publish-site
    failure: ignore
    image: plugins/gh-pages
    settings:
      pages_directory: public/
      username:
        from_secret: github_token
      password: x-oauth-basic
    when:
      branch:
        - main
      event:
        exclude:
          - pull-request

  - name: rebuild-cache-with-filesystem
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: 'filesystem'
      cache_key: '{{ .Repo.Name }}_{{ checksum "go.mod" }}_{{ checksum "go.sum" }}_{{ arch }}_{{ os }}'
      archive_format: 'gzip'
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - 'node_modules'
    volumes:
      - name: cache
        path: /tmp/cache

volumes:
  - name: cache
    temp: {}
