---
kind: pipeline
type: docker
name: default

clone:
  depth: 2

steps:
  - name: install
    image: node:14
    pull: if-not-exists
    commands:
      - yarn

  - name: prebuild
    image: node:14
    commands:
      - yarn lint
      - yarn t

  - name: build
    image: node:14
    commands:
      - yarn build

  - name: publish-site
    failure: ignore
    image: plugins/gh-pages
    settings:
      pages_directory: public/
      username:
        from_secret: github_token
      password: x-oauth-basic
    when:
      branch:
        - main
      event:
        exclude:
          - pull-request
